### ISSUE TITLE
В связи с блокировкой дискорда и наплывом пользователей на площадки.

### ISSUE THREAD

**Issue by PlanNi4** [ImMALWARE/bash-warp-generator#11]
Я правильно понимаю, что имеется возможность сгенерировать warp через vs code? Мне удалось поставить bash терминал, однако конечный warp конфиг получается без PrivateKey, Address и PublicKey.(я не особо разбираюсь во всех этих вещах, поэтому, возможно даже в своем тексте допустил какие-либо ошибки, прошу прощения)

**Comment by ImMALWARE** [comment]
да, похоже огромный наплыв, попробуй позже сгенерировать

**Comment by PlanNi4** [comment]
Я уже сгенерировал, просто рассматриваю возможность помочь своим знакомым. Спасибо за ответ

**Comment by PlanNi4** [comment]
> да, похоже огромный наплыв, попробуй позже сгенерировать

Я уже сгенерировал, просто рассматриваю возможность помочь своим знакомым. Спасибо за ответ
