### ISSUE TITLE
Падает стим при запуске AmneziaWG

### ISSUE THREAD

**Issue by bebruh69** [ImMALWARE/bash-warp-generator#14]
С выключенным AmneziaWG стим работает штатно, при запуске тут же теряет соединение и не подключается

**Comment by ImMALWARE** [comment]
У меня работает

**Comment by bebruh69** [comment]
уже нашел проблему, а именно флаг "Блокировать нетуннелированный трафик"

**Comment by ImMALWARE** [comment]
> уже нашел проблему, а именно флаг "Блокировать нетуннелированный трафик"

Теперь по умолчанию локальная сеть разрешена

**Comment by FForder** [comment]
Могут забанить в CS2 за использование AmneziaWG?

**Comment by ImMALWARE** [comment]
> Могут забанить в CS2 за использование AmneziaWG?

Правилами Steam запрещено использовать VPN, но вроде случаев блокировок не было...
