### ISSUE TITLE
Исключение некоторых IPv4 адресов из списка warp-пируемых

### ISSUE THREAD

**Issue by Qanty228** [ImMALWARE/bash-warp-generator#15]
Как отключить AmneziaWG для некоторый IPv4 адресов, таких как панель управления роутером и т.п.?

**Comment by ImMALWARE** [comment]
Чтобы локальная сеть работала:
![image](https://github.com/user-attachments/assets/7b782a98-46c0-4855-b4b4-bea9efca10b2)
Убираем галочку
![image](https://github.com/user-attachments/assets/4f1e0359-a986-4699-8ee3-35d6cee5736d)

**Comment by ImMALWARE** [comment]
Сделал, чтобы локальная сеть была включена по умолчанию
