### ISSUE TITLE
Пропадает интернет полностью при подключении к туннелю

### ISSUE THREAD

**Issue by ChernyshellyOfficial** [ImMALWARE/bash-warp-generator#16]
Есть какая-то строчка про IPC pipe closed, мб поможет
![image](https://github.com/user-attachments/assets/13f91f80-e2d2-48f7-a331-32af33800a17)

**Comment by ImMALWARE** [comment]
К сожалению, похоже что amneziawg не может обойти блокировку wireguard твоим провайдером. Есть вариант поменять цифры: #5 
Но я не могу эксперементировать, у меня на ростелекоме и теле2 всё работает

**Comment by ivdos** [comment]
@ChernyshellyOfficial оно не с первого раза пробивает. Нужно несколько раз переподключиться.

**Comment by ChernyshellyOfficial** [comment]
Со сменой цифр заработало

**Comment by FFX24** [comment]
> Со сменой цифр заработало

можешь свой конфиг дать пожалуйста?

**Comment by ImMALWARE** [comment]
> Со сменой цифр заработало

Сделал в скрипте по умолчанию другие цифры. @FFX24 и ты попробуй сгенерировать конфиг снова.
