### ISSUE TITLE
Не подключается warp пишет обратитесь к журналу для дополнительной информации

### ISSUE THREAD

**Issue by Aneurysm-source** [ImMALWARE/bash-warp-generator#17]
![image](https://github.com/user-attachments/assets/cfdab926-f938-477f-82fd-e47dbd7e9d21)

**Comment by ImMALWARE** [comment]
это проблема с виндой, покажи скрин журнала

**Comment by Aneurysm-source** [comment]
![image](https://github.com/user-attachments/assets/1f2c1cd0-b546-40d1-8735-e6c13f620025)

**Comment by Aneurysm-source** [comment]
уже пофиксил проблема была в том что у мя все службы были откл
