### ISSUE TITLE
Добавить маркировку пакетов и перенаправлять трафик из приложения в варп

### ISSUE THREAD

**Issue by Top0wl** [ImMALWARE/bash-warp-generator#19]
Вроде же можно маркировать пакеты от приложения? Есть идеи как можно реализовать?

**Comment by Top0wl** [comment]
ChatGPT:

![image](https://github.com/user-attachments/assets/60b2bfa6-dc06-415d-ae85-cc9562f174f0)

**Comment by ImMALWARE** [comment]
Имеются ввиду, пакеты, устанавливаемые через apt install в самом начале? А зачем что-то с ними делать?

> перенаправлять трафик из приложения в варп

можно попробовать импортировать конфиг в amneziavpn и через исключения сделать, чтобы впн был только для определенных приложений

**Comment by Dorlander** [comment]
> Имеются ввиду, пакеты, устанавливаемые через apt install в самом начале? А зачем что-то с ними делать?
> 
> > перенаправлять трафик из приложения в варп
> 
> можно попробовать импортировать конфиг в amneziavpn и через исключения сделать, чтобы впн был только для определенных приложений

Вот да, гайд надо

**Comment by Top0wl** [comment]
AllowedIPs = 162.159.0.0/16, 66.22.0.0/16

Маска конечно огромная, чуть позже переделаю и попробую дописать скрипт, но это позволяет проводить только трафик дискорда через туннель

**Comment by W4BEPMA** [comment]
> > Имеются ввиду, пакеты, устанавливаемые через apt install в самом начале? А зачем что-то с ними делать?
> > > перенаправлять трафик из приложения в варп
> > 
> > 
> > можно попробовать импортировать конфиг в amneziavpn и через исключения сделать, чтобы впн был только для определенных приложений
> 
> Вот да, гайд надо

+1

**Comment by Dorlander** [comment]
> > > Имеются ввиду, пакеты, устанавливаемые через apt install в самом начале? А зачем что-то с ними делать?
> > > > перенаправлять трафик из приложения в варп
> > > 
> > > 
> > > можно попробовать импортировать конфиг в amneziavpn и через исключения сделать, чтобы впн был только для определенных приложений
> > 
> > 
> > Вот да, гайд надо
> 
> +1

Я нашёл погуглил, но чет там все на линуксе делается через судо(

**Comment by lAtaraxl** [comment]
Ну просто закиньте конфиг в AmneziaVPN, там в настройках можно поставить в каких приложениях не нужен впн. К сожалению только это нашел, было бы удобнее если бы была возможность наоборот, выбрать только в каких приложухах мне нужен впн. Второй вариант был бы это закинуть нужные сайты в раздельное туннелирование сайтов, но не робит ибо "сервер по умолчанию не поддерживает раздельное туннелирование"

**Comment by Fa1sEnk** [comment]
> Ну просто закиньте конфиг в AmneziaVPN, там в настройках можно поставить в каких приложениях не нужен впн. К сожалению только это нашел, было бы удобнее если бы была возможность наоборот, выбрать только в каких приложухах мне нужен впн. Второй вариант был бы это закинуть нужные сайты в раздельное туннелирование сайтов, но не робит ибо "сервер по умолчанию не поддерживает раздельное туннелирование"

Да и тут проблема в том, что когда указываешь приложение, в котором не нужен VPN, то в этом приложении вообще нет интернета при включенном AmneziaVPN.

**Comment by lAtaraxl** [comment]
Лог скинь, поглядим. Кстати у меня и у друга трабл что через некоторое время впн отрубается и не хочет врубаться до перезапуска службы, ну и дичька

**Comment by ImMALWARE** [comment]
> Ну просто закиньте конфиг в AmneziaVPN, там в настройках можно поставить в каких приложениях не нужен впн. К сожалению только это нашел, было бы удобнее если бы была возможность наоборот, выбрать только в каких приложухах мне нужен впн. Второй вариант был бы это закинуть нужные сайты в раздельное туннелирование сайтов, но не робит ибо "сервер по умолчанию не поддерживает раздельное туннелирование"

Только такой вариант. Другие приложения вроде не поддерживают AmneziaWG. У меня тоже в AmneziaVPN не работает конфиг. Если такой вариант не подходит, можете попробовать использовать другой способ обхода блокировок: https://t.me/immalware/1193
