### ISSUE TITLE
Укоротить ссылку на скачивание конфига

### ISSUE THREAD

**Issue by fish-dd** [ImMALWARE/bash-warp-generator#2]
**[code.zip](https://github.com/user-attachments/files/16569980/code.zip)**

мой внутренний перфекционист - дебил, поэтому я наговнокодил решение для укорачивания ссылки для скачивания конфига
не бейте ссаными тряпками, я до этого ни разу не кодил ни на жс, ни на баше, и насколько я понял уникальны только приватный ключ и ipv6, но как бы то ни было оно работает лол

п.с. как делать пулл реквесты?

**Comment by fish-dd** [comment]
да, с др кста

**Comment by ImMALWARE** [comment]
> да, с др кста
Спасибо

Не вижу смысла в этом, downloader.html нужен не только для скачивания конфигов, ещё где-нибудь может пригодиться.
