### ISSUE TITLE
Не качается готовый варп с https://immalware.github.io/downloader.html...

### ISSUE THREAD

**Issue by Freak-228** [ImMALWARE/bash-warp-generator#20]
30 минут в очереди на терминаторе отстоял, получил линк а файл не качается. Пробовал через firefox кнопка без реакции, с edge "не удалось загрузить - проблема с сетью". Что сделать можно?

**Comment by kosmokot45** [comment]
Например скопировать текст из терминала, и создать файл WARP.conf

**Comment by ImMALWARE** [comment]
> 30 минут в очереди на терминаторе отстоял, получил линк а файл не качается. Пробовал через firefox кнопка без реакции, с edge "не удалось загрузить - проблема с сетью". Что сделать можно?

https://t.me/immalware_chat/22302 пользователь поделился архивом с конфигами

**Comment by Freak-228** [comment]
> > 30 минут в очереди на терминаторе отстоял, получил линк а файл не качается. Пробовал через firefox кнопка без реакции, с edge "не удалось загрузить - проблема с сетью". Что сделать можно?
> 
> https://t.me/immalware_chat/22302 пользователь поделился архивом с конфигами

А не подскажешь, у тебя в онлайн игрушечках пинг не вырос? Я до этого юзал не свой, у меня пинг в играх +10 мс в среднем. Когда в стим логинился, у меня показывало что попытка входа из МСК, а я не в МСК. Если я свой варп всё таки сгенерю и скачаю, то у меня пинг будет +- как обычно? Или там в любом случае через МСК трафик ведет?

**Comment by ImMALWARE** [comment]
> А не подскажешь, у тебя в онлайн игрушечках пинг не вырос? Я до этого юзал не свой, у меня пинг в играх +10 мс в среднем. Когда в стим логинился, у меня показывало что попытка входа из МСК, а я не в МСК. Если я свой варп всё таки сгенерю и скачаю, то у меня пинг будет +- как обычно? Или там в любом случае через МСК трафик ведет?

Пинг увеличился незначительно. WARP туннелит из МСК, поэтому ничего ненормального в том, что отображается такая попытка входа.

Напомню, что правилами Steam запрещено использовать VPN, так что на страх и риск используй его вместе с Steam... Но, вроде, не было случаев блокировки за VPN (не точно).
