### ISSUE TITLE
Не работает Console

### ISSUE THREAD

**Issue by SensusTenebrae** [ImMALWARE/bash-warp-generator#23]
![image](https://github.com/user-attachments/assets/0ad0a96a-e7a0-4eb9-b9f6-9c11c14c578d)

**Comment by GubernievS** [comment]
зайди под каким нибудь впн, будет работать

**Comment by ImMALWARE** [comment]
Вчера была высокая нагрузка из-за наплыва пользователей. Я убрал Google Cloud Shell из README, так как одного пользователя забанило за использование скрипта. Сейчас уже всё работает, я добавил в README другие варианты, где запускать скрипт.
