### ISSUE TITLE
Рандомизация Jc, Jmin и Jmax

### ISSUE THREAD

**Issue by Verity-Freedom** [ImMALWARE/bash-warp-generator#24]
Во всех сгенерированных конфигах используются одни и те же не у всех работающие значения. Существует генератор который позволяет рандомизировать их по каким-то принципам. Хотелось бы чтобы и скрипт так умел.
https://github.com/teslaproduuction/Amnezia-WireGuard-Tools/releases/tag/v.1.0.0

**Comment by GubernievS** [comment]
нет смысла их рандомизировать

**Comment by Verity-Freedom** [comment]
> нет смысла их рандомизировать

В первую очередь всё зависит от ключа конечно и от их наличия в принципе.

**Comment by ImMALWARE** [comment]
> https://github.com/teslaproduuction/Amnezia-WireGuard-Tools/releases/tag/v.1.0.0

https://www.virustotal.com/gui/file/7f4ffaa8cfbeaec874691d654aee80d5 что-то не прикольно)

Я тоже не вижу смысла их рандомизировать, изначальные значения работают у большинства. Если их как-то поменять — иногда у меня перестаёт работать. А если в скрипте будет рандом... Рабочие конфиги будут сгенерированы только с определённым шансом?
