### ISSUE TITLE
Получено 0 Б

### ISSUE THREAD

**Issue by ERmak148** [ImMALWARE/bash-warp-generator#25]
В большинстве случаев когда пытаюсь подключится через амнезию мне пишет Получено 0 Б и с этим не зайти никуда. Что делать?
Да, и еще
[TUN] [WARP2] peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 2)

**Comment by NazrinsButt** [comment]
Попробуй подставить другие значения в конфиг, информация отсюда вполне себе может пригодится:
https://github.com/ImMALWARE/bash-warp-generator/issues/5
https://github.com/ImMALWARE/bash-warp-generator/issues/24

Паре знакомых помогло.

**Comment by Verity-Freedom** [comment]
Должен быть корректно сгенерированный ключ, попробуй прешэренный конфиг.
https://disk.yandex.ru/d/XcZvsoa5XhgxCA

**Comment by ImMALWARE** [comment]
К сожалению, AmneziaWG не удалось обойти блокировку WireGuard у твоего провайдера. Можно попробовать изменить параметры J в конфиге: https://github.com/ImMALWARE/bash-warp-generator/issues/5
Сейчас в скрипте другие параметры J по умолчанию, попробуй сгенерировать конфиг снова, может, сработает?

Если что-то не получится, напиши в #5

**Comment by Verity-Freedom** [comment]
> Кто нибудь знает рабочие параметры для провайдера Уфанет?

awg 1.5

**Comment by aleksei2202** [comment]
H1 = 337416035
H2 = 774684779
H3 = 1204444769
H4 = 1820629327
