### ISSUE TITLE
Cloud Shell выдает ошибки и null в конфиге

### ISSUE THREAD

**Issue by mracos2** [ImMALWARE/bash-warp-generator#26]
Во время обработки, выводится следующий текст:
![image](https://github.com/user-attachments/assets/ba0eb664-7898-4142-afca-c451f1a06d40)
После обработки оно исчезает и выдает следующее:
![image](https://github.com/user-attachments/assets/7965fa16-87e0-490a-ba08-de0d54bdcc47)
![image](https://github.com/user-attachments/assets/1ae045d7-cf41-47fe-8fe0-bfc185db5318)

**Comment by Verity-Freedom** [comment]
Пробуй на Аезе, там у всех генерировались корректно ключики, можно сгенерировать неограниченное количество за ограниченное время. Смысл именно в уникальности ключа.

**Comment by ImMALWARE** [comment]
Вчера была высокая нагрузка из-за наплыва пользователей. Я убрал Google Cloud Shell из README, так как одного пользователя забанило за использование скрипта. Сейчас уже всё работает, я добавил в README другие варианты, где запускать скрипт.
