### ISSUE TITLE
Cloud Shell Blocked after running this script

### ISSUE THREAD

**Issue by MayMih** [ImMALWARE/bash-warp-generator#27]
![image](https://github.com/user-attachments/assets/934a75b8-9135-467b-8ca6-1609b5d350b2)

Cloud shell blocked for my account next day after I have run this script:

Сервис Google Cloud Shell отключен для вашего аккаунта из-за нарушения [Условий использования](https://cloud.google.com/terms).
Обычно это происходит, если в вашем аккаунте совершаются действия, негативно влияющие на работу сервисов Google Cloud Platform, других пользователей или сетей и серверов Google. К таким действиям относится, например, использование Google Cloud Platform для майнинга криптовалюты и попыток вторжения на сторонние ресурсы.
Если вы считаете, что произошла ошибка, подайте апелляцию.

**Comment by ImMALWARE** [comment]
Видимо, когда все налетели туда с этим скриптом и надудосили, они начали ограничивать. Уберу google cloud shell из гайда, вместо этого распишу другие методы.

**Comment by MayMih** [comment]
Я так и подумал, что дело в этом, решил, что неплохо бы предупредить, чтобы
вас не винили.

On четверг, 10 окт. 2024 г., 18:14, wrote:

> Видимо, когда все налетели туда с этим скриптом и надудосили, они начали
ограничивать. Уберу google cloud shell из гайда, вместо этого распишу
другие методы. — Reply to this email directly, view it on GitHub, or
unsubscribe. You are receiving this because you authored the thread.Message
ID:

С уважением, Михаил
