### ISSUE TITLE
выключается вай-фай

### ISSUE THREAD

**Issue by TGOTKA** [ImMALWARE/bash-warp-generator#28]
Сижу на одном провайдере, на компе все норм (10 винда, лан подключение), а с ноута (вайфай + 11 винда) подключаюсь к шлюзу, потом вырубается вай-фай и пакеты теряются, как это решить?

**Comment by vkhatuntsevv** [comment]
> Сижу на одном провайдере, на компе все норм (10 винда, лан подключение), а с ноута (вайфай + 11 винда) подключаюсь к шлюзу, потом вырубается вай-фай и пакеты теряются, как это решить?

та же самая проблема была. попробуй повторить процесс с скачиванием WARP.conf. я перескачал, сейчас всё работает. не знаю, какая связь должна быть; возможно в разный момент времени немного разный конфиг
