### ISSUE TITLE
Можно ли как-то использовать ключ warp+ с Амнезией, если таковой имеется?

### ISSUE THREAD

**Issue by Radma123** [ImMALWARE/bash-warp-generator#30]

**Comment by Am1hai** [comment]
Можно.
https://github.com/ViRb3/wgcf
https://www.reddit.com/r/CloudFlare/comments/ty9hke/tutorial_how_to_use_warp_or_warp_with_wireguard/
Нужно в wgcf сгенерировать заново приватный ключ и конфиг.
Чтобы вместо warp стало warp+ надо всего-лишь поменять приватный ключ в конфиге AmnesiaWG на новый, отредактировав его прямо в программе.  Сам ключ warp+ в конфиг вписывать не нужно.
Проверять тут https://cloudflareclient.com/cdn-cgi/tracert
в выводе должна быть строчка warp=plus

Скорость в www.speedtest.net будет одинаковая, что с плюсом, что без. У клоудфлейра написано, что на warp+ они более шустро маршрутизируют трафик, если хост реально далеко.

**Comment by ImMALWARE** [comment]
Использовать WARP Plus можно, для этого вам нужен ключ. 
1. Посмотрите инструкцию, как создавать конфиги WARP через wgcf: https://github.com/ViRb3/wgcf
2. Выполните нужные команды в Aeza Terminator или GitHub Codespaces. На своём ПК тоже можно, но только с VPN, РКН заблокировал нужные запросы к Cloudflare!
3. Для вывода текста конфига используем 
```
cat wgcf-profile.conf
```

**Comment by suzver** [comment]
т.е. сам ключ W+ не генерируеца, его нужно доставать из приложения 1.1.1.1 в телефоне?

**Comment by ImMALWARE** [comment]
> т.е. сам ключ W+ не генерируеца, его нужно доставать из приложения 1.1.1.1 в телефоне?

ключи w+ в свободном доступе в интернете, их много
