### ISSUE TITLE
Конфиг не подходит для AmnesiaWG на iOS

### ISSUE THREAD

**Issue by Am1hai** [ImMALWARE/bash-warp-generator#31]
Вот из-за этой строчки
AllowedIPs = 0.0.0.0/1
Надо 0.0.0.0/0

**Comment by ImMALWARE** [comment]
Ооо, так вот почему на айфонах у всех не работает, исправлю)

**Comment by ImMALWARE** [comment]
Теперь скрипт спрашивает, генерировать для iOS или нет
