### ISSUE TITLE
Рекомендую заменить Endpoint = 162.159.193.5:2408

### ISSUE THREAD

**Issue by zabeiua** [ImMALWARE/bash-warp-generator#35]
на  188.114.96.5:2408

**Comment by artuir** [comment]
Сработало

**Comment by kda2495** [comment]
Работает, если порт сменить с 2408 на 500, 1701 или 4500. Но неизвестно, надолго ли.

**Comment by zabeiua** [comment]
Автор пофиксил

**Comment by ImMALWARE** [comment]
> Автор пофиксил

ну, не совсем на тот endpoint)

**Comment by llimonix** [comment]
вроде engage.cloudflareclient.com:2408 снова работает

**Comment by firmshare** [comment]
> вроде engage.cloudflareclient.com:2408 снова работает

Подтверждаю. У меня через сутки этот гейт снова заработал тоже.
