### ISSUE TITLE
Есть ли возможность не использовать гугл шелл?

### ISSUE THREAD

**Issue by EvilBananaH** [ImMALWARE/bash-warp-generator#7]
Есть ли варианты обойтись без консоли гугла, банально гугл заблокирован провайдером и нет возможности им воспользоваться.

**Comment by ImMALWARE** [comment]
Привет, есть 
1 вариант: https://github.com/codespaces
![image](https://github.com/user-attachments/assets/74ba999c-1b85-4508-9083-0126bf7249bb)

2 вариант: https://terminator.aeza.net/en/.
Выбираем Debian, выполняем в терминале 
```apt install sudo```
Затем выполняем команду:
```curl -sSL https://raw.githubusercontent.com/ImMALWARE/bash-warp-generator/main/warp_generator.sh | bash```

**Comment by Mintstorm** [comment]
Второй вариант сработал, спасибо

**Comment by DarkSufferose** [comment]
А могу ли я сделать тоже самое на своем серваке на Ubuntu 22.04?
Скрипт не отрабатывает (

**Comment by OjisanKG** [comment]
На терминаторе тоже пустой конфиг выдал.

**Comment by Cseislvt** [comment]
https://github.com/codespaces - работает, долго пакеты устанавливает в bash но приваткей выдал с ссылкой

**Comment by ImMALWARE** [comment]
> А могу ли я сделать тоже самое на своем серваке на Ubuntu 22.04? Скрипт не отрабатывает (

Только с впн, ркн блокирует запросы, нужные для генерации конфига

**Comment by ImMALWARE** [comment]
Закрою пока этот issue, оставлю открытым только один по этому поводу - #8 
1 вариант: Попытайтесь дождаться google cloud shell.
2 вариант: Попробуйте выполнить на https://terminator.aeza.net/en. Нужно выбрать Debian. Затем выполнить
```apt install sudo```
Затем ```curl -sSL https://raw.githubusercontent.com/ImMALWARE/bash-warp-generator/main/warp_generator.sh | bash```
3 вариант: https://github.com/codespaces 
![image](https://github.com/user-attachments/assets/05ea4857-2937-4098-a271-b4f8f3690d28)
Если нашли ещё варианты, пишите в #8
