### ISSUE TITLE
Невозможно импортировать конфигурацию: Две запятые подряд: ","

### ISSUE THREAD

**Issue by lhaurn** [ImMALWARE/bash-warp-generator#8]
Вылезла проблема в шапке, мб че то не так сделал?

**Comment by DarkSufferose** [comment]
То же самое

**Comment by DarkSufferose** [comment]
Как я понял, скрипт не добавляет айпи

**Comment by ImMALWARE** [comment]
Попробуйте выполнить на https://terminator.aeza.net/en. Нужно выбрать Debian. Затем выполнить 
```apt install sudo```
Затем ```curl -sSL https://raw.githubusercontent.com/ImMALWARE/bash-warp-generator/main/warp_generator.sh | bash```

**Comment by aElDi** [comment]
Скорее всего, не установлен  `jq`
Просто пропиши в консоль:
```bash
sudo apt-get install jq
```
После чего, запусти скрипт еще раз, и скачай новый скачай конфиг

**Comment by ImMALWARE** [comment]
> Скорее всего, не установлен `jq` Просто пропиши в консоль:
> 
> ```shell
> sudo apt-get install jq
> ```
> 
> После чего, запусти скрипт еще раз, и скачай новый скачай конфиг

принял пулл реквест, теперь будет устанавливаться

**Comment by OwnYhide** [comment]
https://github.com/ImMALWARE/bash-warp-generator/issues/9#issuecomment-2400681850

**Comment by ImMALWARE** [comment]
Вчера была высокая нагрузка из-за наплыва пользователей. Я убрал Google Cloud Shell из README, так как одного пользователя забанило за использование скрипта. Сейчас уже всё работает, я добавил в README другие варианты, где запускать скрипт.
