### ISSUE TITLE
Невозможно импортировать конфиг - две запятые подряд.

### ISSUE THREAD

**Issue by OjisanKG** [ImMALWARE/bash-warp-generator#9]
Конфиг делал через codespaces, в самом конфиге двух запятых подряд не видно.

`[Interface]
PrivateKey = dsfgsdfg945fdgdsfg+dgfhjuDFGerG45=
S1 = 0
S2 = 0
Jc = 120
Jmin = 23
Jmax = 911
H1 = 1
H2 = 2
H3 = 3
H4 = 4
Address = , 
DNS = 1.1.1.1, 2606:4700:4700::1111, 1.0.0.1, 2606:4700:4700::1001

[Peer]
PublicKey = 
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = :`

**Comment by ImMALWARE** [comment]
Попробуйте выполнить на https://terminator.aeza.net/en. Нужно выбрать Debian. Затем выполнить 
```apt install sudo```
Затем ```curl -sSL https://raw.githubusercontent.com/ImMALWARE/bash-warp-generator/main/warp_generator.sh | bash```

**Comment by unixty** [comment]
> Попробуйте выполнить на https://terminator.aeza.net/en. Нужно выбрать Debian. Затем выполнить `apt install sudo` Затем `curl -sSL https://raw.githubusercontent.com/ImMALWARE/bash-warp-generator/main/warp_generator.sh | bash`

3 часа ожидания терминала) есть ли способ локально запросить конфиг?

**Comment by ImMALWARE** [comment]
> 3 часа ожидания терминала)

ахренеть, и аёза легла... Тогда github.com/codespaces
![image](https://github.com/user-attachments/assets/92023178-a53f-4c51-9019-1183c3369c0b)


> есть ли способ локально запросить конфиг?

запросы для этого заблокированы ркн, так что нет

**Comment by unixty** [comment]
> > 3 часа ожидания терминала)
> 
> ахренеть, и аёза легла... Тогда https://github.com/codespaces ![image](https://private-user-images.githubusercontent.com/53017160/374648340-92023178-a53f-4c51-9019-1183c3369c0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MDU5OTEsIm5iZiI6MTcyODQwNTY5MSwicGF0aCI6Ii81MzAxNzE2MC8zNzQ2NDgzNDAtOTIwMjMxNzgtYTUzZi00YzUxLTkwMTktMTE4M2MzMzY5YzBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDE2NDEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMTQyMzU1YTM5ZTRkYmUxMDAyNjVlOWQzNTM5YmUyMDQ3N2ZlMjZhMDg2NWIxMzM2ZWI2NWFmNzFiZWZiYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HdGVapqC6MzpQNmH3gfIiQVgVkSJq9DcqWqHhBf89Zo)
> 
> > есть ли способ локально запросить конфиг?
> 
> запросы для этого заблокированы ркн, так что нет

получилось, спасибо) даже локально с впн не получилось почему-то

**Comment by OjisanKG** [comment]
А мне на терминаторе тоже пустой конфиг выдал.

**Comment by OjisanKG** [comment]
> curl -sSL https://raw.githubusercontent.com/ImMALWARE/bash-warp-generator/main/warp_generator.sh | bash

Спасибо, получилось через aeza

**Comment by lhaurn** [comment]
Вы терминал не 3 часа ждать будете, он со временем выпускает юзеров и снижает время, у меня около минут 5-10 заняло

**Comment by DarkRenji** [comment]
> > 3 часа ожидания терминала)
> 
> ахренеть, и аёза легла... Тогда https://github.com/codespaces ![image](https://private-user-images.githubusercontent.com/53017160/374648340-92023178-a53f-4c51-9019-1183c3369c0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MDk1NzUsIm5iZiI6MTcyODQwOTI3NSwicGF0aCI6Ii81MzAxNzE2MC8zNzQ2NDgzNDAtOTIwMjMxNzgtYTUzZi00YzUxLTkwMTktMTE4M2MzMzY5YzBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDE3NDExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0MTJhMGIzNWI3OTFiMzExMGJmNWM3MjE3M2Q4MTFjM2UwZDdmOTk4OTg0YzA4MmFkNGUzZjI2N2MzODk2OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GNe1dHvdaKiZ7Ka6xY2Hf9LT7QFt9d4_bR4glvTwq9Y)
> 
> > есть ли способ локально запросить конфиг?
> 
> запросы для этого заблокированы ркн, так что нет

Спасибо, получилось через гитхаб!

**Comment by ImMALWARE** [comment]
Закрою пока этот issue, оставлю открытым только один по этому поводу - #8 
1 вариант: Попытайтесь дождаться google cloud shell.
2 вариант: Попробуйте выполнить на https://terminator.aeza.net/en. Нужно выбрать Debian. Затем выполнить
```apt install sudo```
Затем ```curl -sSL https://raw.githubusercontent.com/ImMALWARE/bash-warp-generator/main/warp_generator.sh | bash```
3 вариант: https://github.com/codespaces 
![image](https://github.com/user-attachments/assets/05ea4857-2937-4098-a271-b4f8f3690d28)
Если нашли ещё варианты, пишите в #8

**Comment by OwnYhide** [comment]
Если вдруг у кого-то не грузится ни один CodeSpace. Можете попробовать собрать Docker Image и запустить скрипт там: 

`mkdir warp-generator-docker`
`cd warp-generator-docker`

Далее создаёте Dockerfile: 

`New-Item -Name "Dockerfile" -ItemType "file"` - команда для Windows. 

Открывает файл для редактирования:

`notepad Dockerfile`

Записываем в содержимое файле следующее: 

```
FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y curl wireguard-tools jq && \
    apt-get clean

CMD ["bash", "-c", "curl -sSL https://raw.githubusercontent.com/ImMALWARE/bash-warp-generator/main/warp_generator.sh | bash"]`
```

Собираем образ: 

`docker build -t warp-generator-image .
`

И далее просто запускаете контейнер: 

`docker run --privileged --rm warp-generator-image
`

**Comment by ivdos** [comment]
> Конфиг делал через codespaces, в самом конфиге двух запятых подряд не видно.

Потому что не установлена jq зависимость. У гугла клауд шелл оно есть, в других местах нет. Поэтому скрипт желательно подправить.

**Comment by m1rax** [comment]
Невозможно импортировать конфигурацию ключ должен иметь значение PrivateKey=

**Comment by OwnYhide** [comment]
> Невозможно импортировать конфигурацию ключ должен иметь значение PrivateKey=

При исполнении скрипта у тебя пары ключей не сгенерировались. В консоли ошибки есть какие-нибудь? 

Также возможно у тебя jq утилита не установлена:

`sudo apt-get install jq`

**Comment by ImMALWARE** [comment]
> Также возможно у тебя jq утилита не установлена:
> 
> `sudo apt-get install jq`

Скрипт теперь по умолчанию устанавливает jq.
